title: 일단 시작
email: mhk01029433022@gmail.com
description: 개발 개미가 되고픈 베짱이
author: hankook moon
baseurl:            "/"
url:                "https://hankookmoon.run.goorm.io"

# Social Profiles
twitter_username:   
github_username:    hankookmoon
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:  # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
